const w : number = window.innerWidth
const h : number = window.innerHeight
const scGap : number = 0.05
const scDiv : number = 0.51
const strokeFactor : number = 90
const sizeFactor : number = 2.9
const nodes : number = 5
const lines : number = 4
const deg : number = Math.PI / 4
const foreColor : string = "#311B92"
const backColor : string = "#BDBDBD"
